from .harming_commands_detector import HarmingCommandsDetectorPlugin
from .ip_address_usage_detector import IPAddressUsageDetectorPlugin
from .misspell_detector import MisspellDetectorPlugin
from .network_detection_command_detector import NetworkDetectionCommandDetectorPlugin
from .passwd_command_detector import PasswdCommandDetectorPlugin
from .search_command_detector import SearchCommandDetectorPlugin
from .download_command_detector import DownloadCommandDetectorPlugin
from .deleting_tracks_detector import DeletingTracksDetectorPlugin
